### ISSUE TITLE
[Bug] Songs not playing on dubble click on songs page

### ISSUE THREAD

**Issue by Sanderstarr** [somebeaver/Cardinal-Music#1]
When I start the app (windows 10) switch to the songs page I can doubble click on songs to play them.
But when I do that and switch between pages and go back to the songs page doubble clicking the songs doesn't work anymore.

**Comment by somebeaver** [comment]
Confirmed the bug on my end.

In the mean time, Ctrl+clicking the Songs link to hard refresh the view will make double click work again, but the cached scroll position will be lost.

**Comment by somebeaver** [comment]
Wontfix because page this table is being replaced with a better one soon.
